language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install: "pip install -r requirements.txt"
before_script: 
    - "cp chalktalk/secret_settings.py.example chalktalk/secret_settings.py"
    - "echo 'DATABASE_URL = \"sqlite:///dummy.db\"' > chalktalk/settings.py"
script: "python -m unittest discover"
